spring.profiles.active=dev
spring.application.name=todoApp
app.profile.name=Production

server.port=2000
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/food
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.show-sql=true